Update info.yml and composer.json to indicate Drupal 10 compatibility
SU-SWS/jumpstart_ui pull request #131
Opened 2023-08-09 17:46 UTC by cobadger-aten

# READY FOR REVIEW
- One aspect for the module's maintainers to consider is whether to deprecate support for Drupal ^8.8. This PR does not remove that support.

# Summary
- In preparing the fsh.stanford.edu site for Drupal 10 I saw that the contrib module [upgrade_status](https://drupal.org/project/upgrade_status) recommended changes to the info.yml and composer.json files to indicate that the module is compatible with Drupal 10. The upgrade_status module recommended no other changes; I have not independently reviewed the module's code base for further Drupal 10 incompatibilities.

# Review By 10/1/2023
- Drupal 9 reaches end of life in November of 2023. Sites that use this module will need to patch it in it current state in order to use it in sites that are upgraded to Drupal 10.

# Criticality
- Changes to this module's .info.yml and composer.json files are critical for sites that use the module and are upgrading from Drupal 9 to Drupal 10.

# Urgency
- Normal

# Review Tasks

## Setup tasks and/or behavior to test

1. In a Drupal 9 site that uses this module, patch the module using this pull request's diff
2. Install and enable the upgrade_status module
3. At /admin/reports/upgrade-status scan the jumpstart_ui module, then observe that it does not report problems associated with the .info.yml or composer.json files.

### Site Configuration Sync

- No config sync implications

## Front End Validation
- There are no front end implications to this PR.

## Backend / Functional Validation
### Code
- [yes] Are the naming conventions following our standards?
- [yes] Does the code have sufficient inline comments?
- [no] Is there anything in this code that would be hidden or hard to discover through the UI?
- [no] Are there any [code smells](https://blog.codinghorror.com/code-smells/)?
- [no] Are tests provided? eg (unit, behat, or codeception)

### Code security
- [n/a] Are all [forms properly sanitized](https://www.drupal.org/docs/8/security/drupal-8-sanitizing-output)?
- [y] Any obvious [security flaws or new areas for attack](https://www.drupal.org/docs/8/security)?
> This pull request does not remove support for Drupal ^8.8. Drupal 8 is no longer supported. 

## General
- [no] Is there anything included in this PR that is not related to the problem it is trying to solve?
- [yes] Is the approach to the problem appropriate?

# Affected Projects or Products
- The fsh.stanford.edu project uses this module.

# Associated Issues and/or People
- Steven Sangervasi

2023-08-15 22:51 UTC, pookmish requested changes
There are additional changes required to be Drupal 10 prepared for this module. I believe the main thing is replacing `spaceless` in the template files. See [this drupal core issue](https://www.drupal.org/project/drupal/issues/3094850).
I believe that should be the only other issues.

2023-08-18 22:12 UTC, cobadger-aten commented
@pookmish Thanks for your note. I don't find that the {{ spaceless }} filter is used in any templates in jumpstart_ui. I scanned this module with upgrade_status after patching it with the patch from this PR and the only problem that upgrade_status reported was:

>  Cannot redeclare dt() (previously declared in /app/docroot/modules/custom/stanford_ssp/tests/modules/stanford_ssp_test/stanford_ssp_test.module:12)

Which seems to be a bug with upgrade_status, if you ask me, because that dt() definition is inside a conditional that should make sure that the function isn't redeclared.

2023-08-18 22:15 UTC, pookmish commented
@cobadger-aten Here's one example: https://github.com/SU-SWS/jumpstart_ui/blob/8.x/dist/templates/decanter/components/secondary-nav/secondary-nav.twig#L18

We've addressed the spaceless issue in Decanter, the originating library, but we no longer really maintain this module as we've adopted it elsewhere in our codebase.

2023-08-18 22:19 UTC, cobadger-aten commented
Oh, indeed. Revised patch forthcoming.

2023-08-21 13:29 UTC, cobadger-aten commented
Updated pull request to remove calls to twig 'spaceless' filter per https://www.drupal.org/project/drupal/issues/3094850.

2023-08-25 17:09 UTC, pookmish approved these changes
Thanks.

2023-08-25 17:09 UTC, merged