D8CORE-330 Validate field name length
SU-SWS/jumpstart_ui pull request #2
Opened 2019-08-26 17:06 UTC by pookmish

# READY FOR REVIEW

# Summary
- Validate in the UI for field name length to avoid table hashing.

# Needed By (Date)
- asap

# Urgency
- Medium

# Steps to Test
1. you might have to enable ECK to test this.
1. create an eck entity type with a decently long machine name
1. create a field on that with a long name
1. validate the form throws an error.

# See Also
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)

2019-08-26 17:07 UTC, pookmish commented
why you no codeclimate?

2019-08-28 20:34 UTC, sherakama commented on jumpstart_ui.module
> +function jumpstart_ui_field_storage_add_validate(&$form, FormStateInterface $form_state) {
🤔 I'm not sure this belongs here. The jumpstart_ui module is for visual changes and not site building practices but where to put it?

2019-08-28 20:35 UTC, pookmish commented on jumpstart_ui.module
> +function jumpstart_ui_field_storage_add_validate(&$form, FormStateInterface $form_state) {
ya i figured since this will be everywhere. its either here or in `stanford_profile`

2019-08-28 20:52 UTC, sherakama requested changes
Please remove the alter from this PR and create a new module for it called `stanford_fields`

2019-08-30 18:50 UTC, closed without merging