Update one-column.html.twig
SU-SWS/jumpstart_ui pull request #44
Opened 2020-03-04 17:19 UTC by sherakama

# READY FOR REVIEW/NOT READY
- (Edit the above to reflect status)

# Summary
- TL;DR - what's this PR for?

# Needed By (Date)
- When does this need to be merged by?

# Urgency
- How critical is this PR?

# Steps to Test

1. Do this
1. Then this
2. Then this

# Affected Projects or Products
- Does this PR impact any particular projects, products, or modules?

# Associated Issues and/or People
- JIRA ticket
- Other PRs
- Any other contextual information that might be helpful (e.g., description of a bug that this PR fixes, new functionality that it adds, etc.)
- Anyone who should be notified? (`@mention` them here)

# See Also
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)

2020-03-04 22:55 UTC, jbickar requested changes
IIRC this 502 was caused by end-user actions, thus this is a bug fix, thus this needs a regression test.

2020-03-04 23:03 UTC, sherakama commented
This leads to the question. How does one unit test twig templates? Either that or a very long behat test.

2020-03-05 02:24 UTC, sherakama commented
@jbickar Ready for review.

2020-03-05 03:06 UTC, pookmish approved these changes
Confirmed the tests fail with the `8.x-1.x` version of the templates.

2020-03-05 03:07 UTC, merged

2020-03-05 05:30 UTC, sherakama commented
Smashing.

2020-03-05 18:06 UTC, jbickar reviewed
Tank yew.

2020-03-06 17:30 UTC, sherakama commented
Ya'll missed the smashmouth nod in this PR. I am very disappointed.

2020-03-06 17:32 UTC, sherakama commented on tests/src/Kernel/Layout/ThreeColLayoutTest.php
> +    $this->assertText("Im looking for the right class to base my tests off of and I wanna go straight to bed");
https://youtu.be/L_jWHffIx5E?t=34